name: Build Poco F1 (beryllium) 4.19 Kernel with KernelSU-Next (Fixed)

on:
  workflow_dispatch:

env:
  TZ: America/New_York
  KERNEL_REPO: https://github.com/nobiti/Poco-F1-KSUN-4.19-Kernel-Builder

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Debug: show branches
        run: |
          echo "Listing branches in repo:"
          git ls-remote --heads "${{ env.KERNEL_REPO }}"

      - name: Clone kernel source
        run: |
          git clone "${{ env.KERNEL_REPO }}" android-kernel --depth=1
          cd android-kernel
          echo "Checked out branch: $(git rev-parse --abbrev-ref HEAD)"

      # rest of your build steps...
      # (setup environment, KernelSU-Next, build, AnyKernel3 packaging, upload)
